name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out code recursively
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        touch local.properties
        ./gradlew build
